name: Scheduled Script Run

on:
  schedule:
    # Runs at 9 AM UTC daily
    - cron: '0 9 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Uncomment if you have requirements.txt
        # pip install -r requirements.txt

    - name: Run script
      run: |
        python main.py
